firstname = input ("Enter Your First Name:")
lastname = input ("Enter Your Surname:")
Middlename = input ("Enter Your Middle name:") 
DateofBirth = input ("Enter Your Date of birth:")
Stateoforigin = input ("Enter Your State of origin:") 
Age = input ("Enter your age:")
Parentname = input("Enter your parents name:")
LocalGovernmentArea = input("Enter your Local Govenment Area:")
DateOfResumption = input("Enter the Date you resumed:")
DateOfClosure = input ("Enter the date of closure:")
Hobbies = input("Enter your hobbies:")
CourseofStudy = input("Enter your course of study:")
Department = input("Enter your Department:")
Level = input ("Enter your level:")
NameOfKin = input ("Enter the name of your kin:")
print (firstname,lastname,Middlename,DateofBirth, Stateoforigin,Age,Parentname,LocalGovernmentArea,DateOfResumption,DateOfClosure,Hobbies,CourseofStudy,Department,Level,NameOfKin)