nameofstudent = input("Enter your names:")
age  = input("Enter your age:")
studentaddress = input("Enter your address:")
dateofresumption = input("Enter your resumption date:")
studentslevel = input("Enter your level:")
courseofstudy = input("Enter the course your want to study:")
department = input("Enter your department:")
falculty = input("Enter your falcuty:")
nameofschoolappliedfor = input("Enter the name of school applied for:")
dateofclosure = input("Enter your date of closure:")
print(nameofstudent,age,studentaddress,dateofresumption,studentslevel,courseofstudy,department,falculty,nameofschoolappliedfor,dateofclosure)